services:
  mesh:
    image: ubuntu:24.04
    container_name: mesh
    ports:
      - "4001:4001"
    volumes:
      - ./setup_script.sh:/setup_script.sh
    command: bash -c "chmod +x /setup_script.sh && /setup_script.sh && bash"
    tty: true
    stdin_open: true
    restart: unless-stopped