services:
  mesh:
    image: ubuntu:24.04
    container_name: mesh
    networks:
      - haf-network
    ports:
      - "4001:4001"
    volumes:
      - ./setup_script.sh:/setup_script.sh
    command: bash -c "chmod +x /setup_script.sh && /setup_script.sh && bash"
    tty: true
    stdin_open: true
    restart: unless-stopped
    hostname: haf-postgres-container  # This hostname will be used by other services

networks:
  haf-network:
    external: true